### ISSUE TITLE
Rework

### ISSUE THREAD

**Issue by BenNottelling** [BenNottelling/Netflix-Proxy#2]
Ok, so right now this basically does nothing. I'd like to do a few things to it before trying to improve functionality 
1, Rebuild the home page, login page, and build the base for others (such as watch, browse, ect)
2, update the proxy script that's included with this. It's got a bunch of fixes and improvments that actually let it login to netflix by itself, but you can't watch anything because of websockets.  https://github.com/BenNottelling/miniProxy/tree/master

**Comment by BenNottelling** [comment]
This is now done as of commit https://github.com/BenNottelling/Netflix-Proxy/commit/cbe69cedbcb773a35a1d881c99da260830f5c644

**Comment by bionichuman** [comment]
Cool...
